[package]
name = "webauthn-rs"
version = "0.1.3"
authors = ["William Brown <william@blackhats.net.au>"]
edition = "2018"
build = "build.rs"

description = "Webauthn Framework for Rust Web Servers"
# documentation = "..."
# homepage = "..."
repository = "https://github.com/Firstyear/webauthn-rs"
readme = "README.md"
keywords = ["webauthn", "authentication"]
categories = ["authentication", "web-programming"]
license = "MPL-2.0"

[dependencies]
base64 = "0.2"
# byteorder = "1.2"
nom = "4.2"
serde = "1.0"
serde_bytes = "0.10"
serde_cbor = "0.9"
serde_derive = "1.0"
serde_json = "1.0"
# We could consider replacing this with openssl rand.
openssl = "0.10"
rand = "0.6"

[dev-dependencies]
askama = "0.6"

actix = "0.7"
actix-web = "0.7"

futures = "0.1"
env_logger = "0.6"

