[package]
name = "webauthn-rs"
version = "0.1.0"
authors = ["William Brown <william@blackhats.net.au>"]
edition = "2018"
build = "build.rs"

[dependencies]
byteorder = "1.2"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
serde_cbor = "0.9"
serde_bytes = "0.10"
sha2 = "0.8"
base64 = "0.10"
rand = "0.6"


[dev-dependencies]
askama = "0.6"

actix = "0.7"
actix-web = "0.7"

futures = "0.1"
env_logger = "0.6"


[build-dependencies]
askama = "0.6"
